### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by caoziyang1997** [Syuling/PMPro#1]
/root/zhaojia/PMPro/engine/clip/clip.py:23: UserWarning: PyTorch version 1.7.1 or higher is recommended
  warnings.warn("PyTorch version 1.7.1 or higher is recommended")
usage: features.py [-h] [--data_dir DATA_DIR] [--indices_dir INDICES_DIR] [--feature_dir FEATURE_DIR] [--result_dir RESULT_DIR]
                   [--dataset {oxford_pets,oxford_flowers,fgvc_aircraft,dtd,eurosat,stanford_cars,food101,sun397,caltech101,ucf101,imagenet,imagenetv2,imagenet_sketch,imagenet_a,imagenet_r}]
                   [--train-shot TRAIN_SHOT] [--beta BETA] [--seed SEED] [--clip-encoder {ViT-B/16,ViT-B/32,RN50,RN101,RN50x4,RN50x16}]
                   [--image-layer-idx {0,1,-1}] [--text-layer-idx {0,1,-1}] [--text-augmentation {hand_crafted,classname,vanilla,template_mining}]
                   [--image-augmentation {none,flip,randomcrop}] [--image-views IMAGE_VIEWS] [--test-batch-size TEST_BATCH_SIZE] [--num-workers NUM_WORKERS]       
                   [--modality {cross_modal,uni_modal}] [--classifier_head {linear,adapter}] [--classifier_init {zeroshot,random}] [--logit {4.60517,4.0}]
                   [--hyperparams {linear,adapter,partial}]
features.py: error: argument --beta: invalid float value: ''

看看这个问题怎么解决

**Comment by caoziyang1997** [comment]
方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊

**Comment by Syuling** [comment]
您好，是哪里有问题呢？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月17日 08:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [Syuling/PMPro] problem (Issue #1) |

方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊

**Comment by caoziyang1997** [comment]
> 您好，是哪里有问题呢？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年09月17日 08:58 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

方便把你们实验中跑的原始数据给我参考嘛？

**Comment by Syuling** [comment]
您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月17日 09:06 |
| 收件人 | ***@***.***> |
| 抄送至 | Yuling ***@***.***>***@***.***> |
| 主题 | Re: [Syuling/PMPro] problem (Issue #1) |

您好，是哪里有问题呢？
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

方便把你们实验中跑的原始数据给我参考嘛？

**Comment by caoziyang1997** [comment]
> 您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年09月17日 09:06 | | 收件人 | ***@***.***> | | 抄送至 | Yuling ***@***.***>***@***.***> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。

**Comment by caoziyang1997** [comment]
在运行bash features.sh 脚本时候报错
python features.py --dataset fgvc_aircraft --train-shot 16 --seed 1 --clip-encoder RN50 --image-layer-idx 0 --text-augmentation hand_crafted --image-augmentation none --image-views 0
/root/zhaojia/PMPro/engine/clip/clip.py:23: UserWarning: PyTorch version 1.7.1 or higher is recommended
  warnings.warn("PyTorch version 1.7.1 or higher is recommended")
Traceback (most recent call last):
  File "features.py", line 360, in <module>
    choices=dataset_classes.keys(),
NameError: name 'dataset_classes' is not defined
您有时间帮我看看这个问题，非常感谢谢

**Comment by Syuling** [comment]
OK，这两天发给您。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月17日 09:12 |
| 收件人 | ***@***.***> |
| 抄送至 | Yuling ***@***.***>***@***.***> |
| 主题 | Re: [Syuling/PMPro] problem (Issue #1) |

您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:06 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。

**Comment by caoziyang1997** [comment]
> OK，这两天发给您。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年09月17日 09:12 | | 收件人 | ***@***.***> | | 抄送至 | Yuling ***@***.***>***@***.***> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:06 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

非常感谢，祝您中秋快乐

**Comment by caoziyang1997** [comment]
> > OK，这两天发给您。
> > […](#)
> > ---- 回复的原邮件 ---- | 发件人 | _**@**_._**> | | 日期 | 2024年09月17日 09:12 | | 收件人 | _**@**_.**_> | | 抄送至 | Yuling _**@**_._**>**_@_**.**_> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:06 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @._**> 指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.**_>
> 
> 非常感谢，祝您中秋快乐

**Comment by caoziyang1997** [comment]
> OK，这两天发给您。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年09月17日 09:12 | | 收件人 | ***@***.***> | | 抄送至 | Yuling ***@***.***>***@***.***> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:06 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

您好，打扰您了，请问您现在有时间把实验数据（1，2，4，8，16shots）发我嘛，非常感谢

**Comment by Syuling** [comment]
嗨喽，同学，早上发给你了，你没收到吗？







在 2024-09-18 15:29:38，"yy_tiny" ***@***.***> 写道：

OK，这两天发给您。
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:12 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:06 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

您好，打扰您了，请问您现在有时间把实验数据（1，2，4，8，16shots）发我嘛，非常感谢

**Comment by caoziyang1997** [comment]
> 嗨喽，同学，早上发给你了，你没收到吗？ 在 2024-09-18 15:29:38，"yy_tiny" ***@***.***> 写道： OK，这两天发给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:12 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:06 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 您好，打扰您了，请问您现在有时间把实验数据（1，2，4，8，16shots）发我嘛，非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

非常抱歉，早上我这边没有收到有关于您发给我的实验数据消息，可否再发一遍，实在是麻烦您了。

**Comment by Syuling** [comment]
刚才发了，看附件。




在 2024-09-18 15:50:52，"yy_tiny" ***@***.***> 写道：

嗨喽，同学，早上发给你了，你没收到吗？ 在 2024-09-18 15:29:38，"yy_tiny" @.> 写道： OK，这两天发给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:12 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您的原始数据指的是数据集还是实验数据？还在放假中，可能得明后两天给您。 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 09:06 | | 收件人 | @.> | | 抄送至 | Yuling @.>@.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 您好，是哪里有问题呢？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年09月17日 08:58 | | 收件人 | @.> | | 抄送至 | @.> | | 主题 | Re: [Syuling/PMPro] problem (Issue #1) | 方便把你们实验的原始数据发来嘛，跑的实验出入有点大啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> 方便把你们实验中跑的原始数据给我参考嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 指的是实验数据（我想拿过来参考一下），按照readme.md执行操作，有太多错误，还没跑通。非常感谢。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 您好，打扰您了，请问您现在有时间把实验数据（1，2，4，8，16shots）发我嘛，非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

非常抱歉，早上我这边没有收到有关于您发给我的实验数据消息，可否再发一遍，实在是麻烦您了。

**Comment by caoziyang1997** [comment]
可是我这边确实没有收到附件，不知道是不是账号问题。如果方便的话，请发到我的另一个邮箱” 
   23221409@fynu.edu.cn     “ ，非常感谢，麻烦您了，同学！
